### ISSUE TITLE
Distinguish between left and right hands

### ISSUE THREAD

**Issue by penincillin** [ddshan/hand_detector.d2#1]
Hi

Thanks for releasing the wonderful work !

I have a question about hand type. Is there any way to distinguish the left hand between the right one ?

Thanks !

**Comment by ddshan** [comment]
Hi,

This repo is only about hand detection models. If you want to classify left and right hands, I encourage you to take a look at https://github.com/ddshan/hand_object_detector.  Hope this is helpful.

**Comment by ddshan** [comment]
Hi,

This repo is only about hand detection models. If you want to classify left and right hands, I encourage you to take a look at https://github.com/ddshan/hand_object_detector. Hope this is helpful.
