### ISSUE TITLE
OMG model is too good and speed is too bad

### ISSUE THREAD

**Issue by muhammadabdullah34907** [ddshan/hand_detector.d2#3]
Hi @ddshan 
  you have done a great job gathering different datasets and trained on large size network like Faster RCNN with 101 back Xception as backbone. I was wondering how useful this model can be if some wants to deploy it on nvidia jetson TX2 or Xaiver or NX etc. Because speed is such an issue here. I have tested the model on jetson tx2 but the speed is less then 1 fps. Did you try to optimize the model ro have plans near in future ? For example: 
https://github.com/facebookresearch/detectron2/tree/master/tools/deploy

have you also trained on networks with backbone MobilenetV2 ?

I would really appreciate if you could tell me how to improve the speed on jetson tx2 ?

**Comment by lucasjinreal** [comment]
@muhammadabdullah34907 If you can have the data, I can train a faster and accurate hand detector

**Comment by ddshan** [comment]
Hi @muhammadabdullah34907 
I added [demo_batch.py](https://github.com/ddshan/hand_detector.d2/blob/master/demo_batch.py) file in the repo to do batch prediction. It can process several images together at a time which improves the speed a lot. Please let me know if this solves your speed problem. 

We always want to optimize the model if possible. Currently, we do not have the plan to do the deployment.

**Comment by muhammadabdullah34907** [comment]
@jinfagang do you have any update on this ?
